export interface RecommendationItem {
  id: number;
  image: string;
  title: string;
  price: string;
  location: string;
  publishDate: string;
  details: string;
  alt: string;
}

export const mockRecommendations: RecommendationItem[] = [
  {
    id: 1,
    image: 'assets/images/ad-picture_1.png',
    title: 'Гитара Fender',
    price: '20 000 Р',
    location: 'Москва, Ленинский проспект',
    publishDate: 'Сегодня 14:12',
    details: 'Это подробное описание товара!',
    alt: 'adPicture',
  },
  {
    id: 2,
    image: 'assets/images/ad-picture_2.png',
    title: 'Apple iPhone 15 Pro',
    price: '75 999 Р',
    location: 'Казань, Ленинский проспект',
    publishDate: 'Вчера 09:02',
    details: 'Это подробное описание товара!',
    alt: 'adPicture',
  },
  {
    id: 3,
    image: 'assets/images/ad-picture_3.png',
    title: 'Детская игрушка ХаггиВагги',
    price: '560 Р',
    location: 'Севастополь',
    publishDate: 'Сегодня 18:20',
    details: 'Это подробное описание товара!',
    alt: 'adPicture',
  },
  {
    id: 4,
    image: 'assets/images/ad-picture_1.png',
    title: 'Гитара Fender',
    price: '20 000 Р',
    location: 'Москва, Ленинский проспект',
    publishDate: 'Сегодня 14:12',
    details: 'Это подробное описание товара!',
    alt: 'adPicture',
  },
  {
    id: 5,
    image: 'assets/images/ad-picture_2.png',
    title: 'Apple iPhone 15 Pro',
    price: '75 999 Р',
    location: 'Казань, Ленинский проспект',
    publishDate: 'Вчера 09:02',
    details: 'Это подробное описание товара!',
    alt: 'adPicture',
  },
  {
    id: 6,
    image: 'assets/images/ad-picture_3.png',
    title: 'Детская игрушка ХаггиВагги',
    price: '560 Р',
    location: 'Севастополь',
    publishDate: 'Сегодня 18:20',
    details: 'Это подробное описание товара!',
    alt: 'adPicture',
  },
  {
    id: 7,
    image: 'assets/images/ad-picture_1.png',
    title: 'Гитара Fender',
    price: '20 000 Р',
    location: 'Москва, Ленинский проспект',
    publishDate: 'Сегодня 14:12',
    details: 'Это подробное описание товара!',
    alt: 'adPicture',
  },
  {
    id: 8,
    image: 'assets/images/ad-picture_2.png',
    title: 'Apple iPhone 15 Pro',
    price: '75 999 Р',
    location: 'Казань, Ленинский проспект',
    publishDate: 'Вчера 09:02',
    details: 'Это подробное описание товара!',
    alt: 'adPicture',
  },
  {
    id: 9,
    image: 'assets/images/ad-picture_3.png',
    title: 'Детская игрушка ХаггиВагги',
    price: '560 Р',
    location: 'Севастополь',
    publishDate: 'Сегодня 18:20',
    details: 'Это подробное описание товара!',
    alt: 'adPicture',
  },
  {
    id: 10,
    image: 'assets/images/ad-picture_1.png',
    title: 'Гитара Fender',
    price: '20 000 Р',
    location: 'Москва, Ленинский проспект',
    publishDate: 'Сегодня 14:12',
    details: 'Это подробное описание товара!',
    alt: 'adPicture',
  },
  {
    id: 11,
    image: 'assets/images/ad-picture_2.png',
    title: 'Apple iPhone 15 Pro',
    price: '75 999 Р',
    location: 'Казань, Ленинский проспект',
    publishDate: 'Вчера 09:02',
    details: 'Это подробное описание товара!',
    alt: 'adPicture',
  },
  {
    id: 12,
    image: 'assets/images/ad-picture_3.png',
    title: 'Детская игрушка ХаггиВагги',
    price: '560 Р',
    location: 'Севастополь',
    publishDate: 'Сегодня 18:20',
    details: 'Это подробное описание товара!',
    alt: 'adPicture',
  },
  {
    id: 13,
    image: 'assets/images/ad-picture_1.png',
    title: 'Гитара Fender',
    price: '20 000 Р',
    location: 'Москва, Ленинский проспект',
    publishDate: 'Сегодня 14:12',
    details: 'Это подробное описание товара!',
    alt: 'adPicture',
  },
  {
    id: 14,
    image: 'assets/images/ad-picture_2.png',
    title: 'Apple iPhone 15 Pro',
    price: '75 999 Р',
    location: 'Казань, Ленинский проспект',
    publishDate: 'Вчера 09:02',
    details: 'Это подробное описание товара!',
    alt: 'adPicture',
  },
  {
    id: 15,
    image: 'assets/images/ad-picture_3.png',
    title: 'Детская игрушка ХаггиВагги',
    price: '560 Р',
    location: 'Севастополь',
    publishDate: 'Сегодня 18:20',
    details: 'Это подробное описание товара!',
    alt: 'adPicture',
  },
  {
    id: 16,
    image: 'assets/images/ad-picture_1.png',
    title: 'Гитара Fender',
    price: '20 000 Р',
    location: 'Москва, Ленинский проспект',
    publishDate: 'Сегодня 14:12',
    details: 'Это подробное описание товара!',
    alt: 'adPicture',
  },
];
